package UI;

import POJO.Game;
import POJO.GamePlaysPlayer;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

import static Backend.DBQueries.getAllGamePlaysPlayers;
import static Backend.DBQueries.getAllGames;

public class GamePlaysPlayersWindow {
    private JPanel gamePlaysPlayersPanel;
    private JTable gamePlaysPlayersTable;

    public GamePlaysPlayersWindow() {
        String[] columnNames = {"PLAY ID",
                "GAME ID",
                "PLAYER ID"};
        DefaultTableModel model = new DefaultTableModel();
        gamePlaysPlayersTable.setModel(model);
        model.setColumnIdentifiers(columnNames);
        List<GamePlaysPlayer> allGames = getAllGamePlaysPlayers();
        for (GamePlaysPlayer s : allGames) {
            Object[] o = new Object[3];
            o[0] = s.getPlayId();
            o[1] = s.getGameId();
            o[2] = s.getPlayerId();
            model.addRow(o);
        }
    }

    public JPanel getGamePlaysPlayersPanel() {
        return gamePlaysPlayersPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        gamePlaysPlayersPanel = new JPanel();
        gamePlaysPlayersPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        gamePlaysPlayersPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        gamePlaysPlayersTable = new JTable();
        scrollPane1.setViewportView(gamePlaysPlayersTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return gamePlaysPlayersPanel;
    }
}
