package UI;

import POJO.GamePlaysPlayer;
import POJO.GameTeam;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

import static Backend.DBQueries.getAllGamePlaysPlayers;
import static Backend.DBQueries.getAllGameTeams;

public class GameTeamsWindow {
    private JPanel gameTeamsPanel;
    private JTable gameTeamsTable;

    public GameTeamsWindow() {
        String[] columnNames = {"WON",
                "HEAD COACH",
                "GOALS",
                "SHOTS",
                "HITS",
                "GAME ID",
                "TEAM ID"};
        DefaultTableModel model = new DefaultTableModel();
        gameTeamsTable.setModel(model);
        model.setColumnIdentifiers(columnNames);
        List<GameTeam> gameTeams = getAllGameTeams();
        for (GameTeam s : gameTeams) {
            Object[] o = new Object[7];
            o[0] = s.getWon();
            o[1] = s.getHeadCoach();
            o[2] = s.getGoals();
            o[3] = s.getShots();
            o[4] = s.getHits();
            o[5] = s.getGameId();
            o[6] = s.getTeamId();
            model.addRow(o);
        }
    }

    public JPanel getGameTeamsPanel() {
        return gameTeamsPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        gameTeamsPanel = new JPanel();
        gameTeamsPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        gameTeamsPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        gameTeamsTable = new JTable();
        scrollPane1.setViewportView(gameTeamsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return gameTeamsPanel;
    }
}
