package UI;

import POJO.GamePlaysPlayer;
import POJO.TeamInfo;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

import static Backend.DBQueries.getAllGamePlaysPlayers;
import static Backend.DBQueries.getAllTeamsInfo;

public class TeamInfoWindow {
    private JPanel teamInfoPanel;
    private JTable teamInfoTable;

    public TeamInfoWindow() {
        String[] columnNames = {"TEAM ID",
                "FRANCHISE ID",
                "SHORT NAME",
                "TEAM NAME",
                "ABBREVIATION"};
        DefaultTableModel model = new DefaultTableModel();
        teamInfoTable.setModel(model);
        model.setColumnIdentifiers(columnNames);
        List<TeamInfo> teamsInfo = getAllTeamsInfo();
        for (TeamInfo s : teamsInfo) {
            Object[] o = new Object[5];
            o[0] = s.getTeamId();
            o[1] = s.getFranchiseId();
            o[2] = s.getShortName();
            o[3] = s.getTeamName();
            o[4] = s.getAbbreviation();
            model.addRow(o);
        }
    }

    public JPanel getTeamInfoPanel() {
        return teamInfoPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        teamInfoPanel = new JPanel();
        teamInfoPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JScrollPane scrollPane1 = new JScrollPane();
        teamInfoPanel.add(scrollPane1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        teamInfoTable = new JTable();
        scrollPane1.setViewportView(teamInfoTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return teamInfoPanel;
    }
}
